# Take ubuntu:latest image as the basis for our custom one
FROM ubuntu
# Install the figlet package with the latest version in the repos of the ubuntu:latest
RUN apt-get update
RUN apt-get install figlet
